name: twitter_clone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^1.3.0
  timeago: ^3.3.0
  flutter_riverpod: ^2.1.3
  state_notifier: ^0.7.2+1
  image_picker: ^0.8.6+1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png